# Generated by Django 5.2.8 on 2025-11-21 06:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatternAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('weekly_trends', models.JSONField(default=dict, help_text='{ day_of_week: { category: quantity } }')),
                ('over_consumption', models.JSONField(default=list, help_text='[ { category, avgQuantity, typicalRange } ]')),
                ('under_consumption', models.JSONField(default=list, help_text='[ { category, daysSinceLastLog } ]')),
                ('waste_risk_items', models.JSONField(default=list, help_text='[ { item, riskScore, reason } ]')),
                ('imbalanced_patterns', models.JSONField(default=list, help_text='[ { category, status, recommendation } ]')),
                ('heatmap_data', models.JSONField(default=dict, help_text='Matrix for visualization [day][category] = quantity')),
                ('total_categories_tracked', models.IntegerField(default=0)),
                ('total_consumption_entries', models.IntegerField(default=0)),
                ('waste_risk_count', models.IntegerField(default=0)),
                ('health_score', models.FloatField(default=0, help_text='Overall consumption health score (0-100)')),
            ],
            options={
                'verbose_name_plural': 'Pattern Analyses',
                'ordering': ['-analysis_date'],
            },
        ),
        migrations.CreateModel(
            name='UserBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('reduce_waste', 'Reduce Waste'), ('balance_diet', 'Balance Diet'), ('shopping_list', 'Shopping List'), ('meal_planning', 'Meal Planning'), ('budget_optimization', 'Budget Optimization')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priority', models.IntegerField(default=1, help_text='1=Low, 2=Medium, 3=High')),
                ('is_read', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('action_items', models.JSONField(default=list, help_text='Specific actions user can take')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this recommendation becomes irrelevant', null=True)),
                ('pattern_analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='mainapp.patternanalysis')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='patternanalysis',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pattern_of_user', to='mainapp.userbase'),
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_period_days', models.IntegerField(default=30, help_text='Number of days to analyze (30, 60, or 90)')),
                ('waste_alert_threshold', models.IntegerField(default=7, help_text='Alert when items expire within X days')),
                ('over_consumption_multiplier', models.FloatField(default=2.0, help_text='Flag consumption as high when > X times typical')),
                ('under_consumption_days', models.IntegerField(default=14, help_text='Flag categories not consumed in X days')),
                ('enable_waste_alerts', models.BooleanField(default=True)),
                ('enable_pattern_insights', models.BooleanField(default=True)),
                ('enable_weekly_summary', models.BooleanField(default=True)),
                ('preferred_units', models.CharField(choices=[('metric', 'Metric'), ('imperial', 'Imperial')], default='metric', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Preferences',
            },
        ),
        migrations.CreateModel(
            name='WasteLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_item', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=200)),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(default='pcs', max_length=10)),
                ('waste_date', models.DateField(default=django.utils.timezone.now)),
                ('reason', models.CharField(choices=[('expired', 'Expired'), ('spoiled', 'Spoiled'), ('excess', 'Bought too much'), ('forgot', 'Forgot about it'), ('other', 'Other')], max_length=50)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated cost of wasted item', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-waste_date'],
                'indexes': [models.Index(fields=['user', 'waste_date'], name='mainapp_was_user_id_d961c6_idx')],
            },
        ),
    ]
