# Generated by Django 5.2.8 on 2025-11-21 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_recommendation_user_alter_userpreferences_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WastePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateField(auto_now_add=True)),
                ('weekly_waste_grams', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('weekly_waste_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monthly_waste_grams', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monthly_waste_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('projected_yearly_grams', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('projected_yearly_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_predictions', to='mainapp.userbase')),
            ],
        ),
    ]
