# Generated by Django 5.2.8 on 2025-11-21 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_wasteprediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_date', models.DateField(auto_now_add=True)),
                ('overall_score', models.FloatField(default=0)),
                ('waste_reduction_score', models.FloatField(default=0)),
                ('nutrition_balance_score', models.FloatField(default=0)),
                ('inventory_utilization_score', models.FloatField(default=0)),
                ('sustainable_practices_score', models.FloatField(default=0)),
                ('insights', models.TextField(blank=True)),
                ('action_steps', models.JSONField(default=list, help_text='[ { title, description, potentialImpact } ]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impact_scores', to='mainapp.userbase')),
            ],
            options={
                'ordering': ['-score_date'],
            },
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField()),
                ('plan_data', models.JSONField(default=list, help_text='[ { day, meals: [ { type, name, ingredients } ] } ]')),
                ('shopping_list', models.JSONField(default=list, help_text='[ { item, quantity, estimatedCost } ]')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('budget_remaining', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nutrition_summary', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to='mainapp.userbase')),
            ],
            options={
                'ordering': ['-week_start_date'],
            },
        ),
    ]
