# Generated by Django 5.2.8 on 2025-11-21 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_impactscore_mealplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='SDGScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField()),
                ('overall_sdg_score', models.FloatField(default=0, help_text='Overall SDG impact score')),
                ('sdg_2_score', models.FloatField(default=0, help_text='SDG 2: Zero Hunger - Nutrition adequacy')),
                ('sdg_3_score', models.FloatField(default=0, help_text='SDG 3: Good Health - Health impact')),
                ('sdg_12_score', models.FloatField(default=0, help_text='SDG 12: Responsible Consumption - Waste reduction')),
                ('waste_reduction_percentage', models.FloatField(default=0, help_text='% reduction vs community avg')),
                ('nutrition_improvement_percentage', models.FloatField(default=0, help_text='% of RDA met')),
                ('carbon_footprint_score', models.FloatField(default=0, help_text='Estimated carbon impact score')),
                ('weekly_insight', models.TextField(blank=True, help_text='AI-generated weekly summary')),
                ('celebration_message', models.TextField(blank=True, help_text='Motivational message')),
                ('action_steps', models.JSONField(default=list, help_text='[{title, description, potentialImpact, sdg_target, category}]')),
                ('week_over_week_change', models.FloatField(default=0, help_text='Score change from last week')),
                ('trend', models.CharField(choices=[('improving', 'Improving'), ('stable', 'Stable'), ('declining', 'Declining')], default='stable', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdg_scores', to='mainapp.userbase')),
            ],
            options={
                'ordering': ['-week_start_date'],
                'unique_together': {('user', 'week_start_date')},
            },
        ),
    ]
